// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package queries

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
insert into audit_log(from_player_id, to_player_id, kind, from_content, to_content)
  values(?,?,?,?,?)
`

type InsertAuditLogParams struct {
	FromPlayerID string
	ToPlayerID   string
	Kind         string
	FromContent  string
	ToContent    string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.FromPlayerID,
		arg.ToPlayerID,
		arg.Kind,
		arg.FromContent,
		arg.ToContent,
	)
	return err
}

const selectAuditLogs = `-- name: SelectAuditLogs :many
select p1.id, p1.role, p1.alias, p1.soldier_div, p1.demo_div, p1.avatar_url, p1.trade_token, p1.tempus_id, p1.country, p1.country_code, p1.class_pref, p1.map_pref, p1.launcher_pref, p1.created_at, p2.id, p2.role, p2.alias, p2.soldier_div, p2.demo_div, p2.avatar_url, p2.trade_token, p2.tempus_id, p2.country, p2.country_code, p2.class_pref, p2.map_pref, p2.launcher_pref, p2.created_at, l.from_player_id, l.to_player_id, l.kind, l.from_content, l.to_content, l.created_at from audit_log l
join player p1 on p1.id = l.from_player_id
join player p2 on p2.id = l.to_player_id
order by l.created_at desc
`

type SelectAuditLogsRow struct {
	Player   Player
	Player_2 Player
	AuditLog AuditLog
}

func (q *Queries) SelectAuditLogs(ctx context.Context) ([]SelectAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAuditLogsRow
	for rows.Next() {
		var i SelectAuditLogsRow
		if err := rows.Scan(
			&i.Player.ID,
			&i.Player.Role,
			&i.Player.Alias,
			&i.Player.SoldierDiv,
			&i.Player.DemoDiv,
			&i.Player.AvatarUrl,
			&i.Player.TradeToken,
			&i.Player.TempusID,
			&i.Player.Country,
			&i.Player.CountryCode,
			&i.Player.ClassPref,
			&i.Player.MapPref,
			&i.Player.LauncherPref,
			&i.Player.CreatedAt,
			&i.Player_2.ID,
			&i.Player_2.Role,
			&i.Player_2.Alias,
			&i.Player_2.SoldierDiv,
			&i.Player_2.DemoDiv,
			&i.Player_2.AvatarUrl,
			&i.Player_2.TradeToken,
			&i.Player_2.TempusID,
			&i.Player_2.Country,
			&i.Player_2.CountryCode,
			&i.Player_2.ClassPref,
			&i.Player_2.MapPref,
			&i.Player_2.LauncherPref,
			&i.Player_2.CreatedAt,
			&i.AuditLog.FromPlayerID,
			&i.AuditLog.ToPlayerID,
			&i.AuditLog.Kind,
			&i.AuditLog.FromContent,
			&i.AuditLog.ToContent,
			&i.AuditLog.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
