// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition_prize.sql

package queries

import (
	"context"
)

const deleteCompetitionPrize = `-- name: DeleteCompetitionPrize :exec
delete from competition_prize
  where competition_division_id = ?
`

func (q *Queries) DeleteCompetitionPrize(ctx context.Context, competitionDivisionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompetitionPrize, competitionDivisionID)
	return err
}

const insertCompetitionPrize = `-- name: InsertCompetitionPrize :exec
insert into competition_prize (competition_division_id, placement, amount)
  values (?, ?, ?)
`

type InsertCompetitionPrizeParams struct {
	CompetitionDivisionID int64 `json:"competition_division_id"`
	Placement             int64 `json:"placement"`
	Amount                int64 `json:"amount"`
}

func (q *Queries) InsertCompetitionPrize(ctx context.Context, arg InsertCompetitionPrizeParams) error {
	_, err := q.db.ExecContext(ctx, insertCompetitionPrize, arg.CompetitionDivisionID, arg.Placement, arg.Amount)
	return err
}

const selectCompetitionPrizes = `-- name: SelectCompetitionPrizes :many
select id, competition_division_id, placement, amount from competition_prize
  where competition_division_id = ?
`

func (q *Queries) SelectCompetitionPrizes(ctx context.Context, competitionDivisionID int64) ([]CompetitionPrize, error) {
	rows, err := q.db.QueryContext(ctx, selectCompetitionPrizes, competitionDivisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionPrize
	for rows.Next() {
		var i CompetitionPrize
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionDivisionID,
			&i.Placement,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetitionPrize = `-- name: UpdateCompetitionPrize :exec
update competition_prize
  set placement = ?,
  amount = ?
  where competition_division_id = ?
`

type UpdateCompetitionPrizeParams struct {
	Placement             int64 `json:"placement"`
	Amount                int64 `json:"amount"`
	CompetitionDivisionID int64 `json:"competition_division_id"`
}

func (q *Queries) UpdateCompetitionPrize(ctx context.Context, arg UpdateCompetitionPrizeParams) error {
	_, err := q.db.ExecContext(ctx, updateCompetitionPrize, arg.Placement, arg.Amount, arg.CompetitionDivisionID)
	return err
}
