// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition.sql

package queries

import (
	"context"
	"time"
)

const deleteCompetition = `-- name: DeleteCompetition :one
delete from competition
  where id = ? and starts_at > current_timestamp
  returning id, class, starts_at, ends_at, visible_at, complete, created_at
`

func (q *Queries) DeleteCompetition(ctx context.Context, id int64) (Competition, error) {
	row := q.db.QueryRowContext(ctx, deleteCompetition, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Class,
		&i.StartsAt,
		&i.EndsAt,
		&i.VisibleAt,
		&i.Complete,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompetition = `-- name: InsertCompetition :one
insert into competition (class, starts_at, ends_at, visible_at)
  values (?, ?, ?, ?)
  returning id, class, starts_at, ends_at, visible_at, complete, created_at
`

type InsertCompetitionParams struct {
	Class     string    `json:"class"`
	StartsAt  time.Time `json:"starts_at"`
	EndsAt    time.Time `json:"ends_at"`
	VisibleAt time.Time `json:"visible_at"`
}

func (q *Queries) InsertCompetition(ctx context.Context, arg InsertCompetitionParams) (Competition, error) {
	row := q.db.QueryRowContext(ctx, insertCompetition,
		arg.Class,
		arg.StartsAt,
		arg.EndsAt,
		arg.VisibleAt,
	)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Class,
		&i.StartsAt,
		&i.EndsAt,
		&i.VisibleAt,
		&i.Complete,
		&i.CreatedAt,
	)
	return i, err
}

const updateCompetition = `-- name: UpdateCompetition :exec
update competition
  set class = ?,
  starts_at = ?,
  ends_at = ?,
  visible_at = ?
  where id = ?
`

type UpdateCompetitionParams struct {
	Class     string    `json:"class"`
	StartsAt  time.Time `json:"starts_at"`
	EndsAt    time.Time `json:"ends_at"`
	VisibleAt time.Time `json:"visible_at"`
	ID        int64     `json:"id"`
}

func (q *Queries) UpdateCompetition(ctx context.Context, arg UpdateCompetitionParams) error {
	_, err := q.db.ExecContext(ctx, updateCompetition,
		arg.Class,
		arg.StartsAt,
		arg.EndsAt,
		arg.VisibleAt,
		arg.ID,
	)
	return err
}
