// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition_prize.sql

package queries

import (
	"context"
)

const deleteCompetitionDivisionPrizepool = `-- name: DeleteCompetitionDivisionPrizepool :exec
delete from competition_prize
  where competition_division_id = ?
`

func (q *Queries) DeleteCompetitionDivisionPrizepool(ctx context.Context, competitionDivisionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompetitionDivisionPrizepool, competitionDivisionID)
	return err
}

const deleteCompetitionPrize = `-- name: DeleteCompetitionPrize :exec
delete from competition_prize
  where id = ?
`

func (q *Queries) DeleteCompetitionPrize(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompetitionPrize, id)
	return err
}

const insertCompetitionPrize = `-- name: InsertCompetitionPrize :exec
insert into competition_prize (competition_division_id, placement, amount)
  values (?, ?, ?)
`

type InsertCompetitionPrizeParams struct {
	CompetitionDivisionID int64 `json:"competition_division_id"`
	Placement             int64 `json:"placement"`
	Amount                int64 `json:"amount"`
}

func (q *Queries) InsertCompetitionPrize(ctx context.Context, arg InsertCompetitionPrizeParams) error {
	_, err := q.db.ExecContext(ctx, insertCompetitionPrize, arg.CompetitionDivisionID, arg.Placement, arg.Amount)
	return err
}

const selectDivisionPrizepool = `-- name: SelectDivisionPrizepool :many
select cp.id, competition_division_id, placement, amount, cd.id, competition_id, division, map from competition_prize cp
  join competition_division cd on cp.competition_division_id = cd.id
  where cd.id = ?
`

type SelectDivisionPrizepoolRow struct {
	ID                    int64  `json:"id"`
	CompetitionDivisionID int64  `json:"competition_division_id"`
	Placement             int64  `json:"placement"`
	Amount                int64  `json:"amount"`
	ID_2                  int64  `json:"id_2"`
	CompetitionID         int64  `json:"competition_id"`
	Division              string `json:"division"`
	Map                   string `json:"map"`
}

func (q *Queries) SelectDivisionPrizepool(ctx context.Context, id int64) ([]SelectDivisionPrizepoolRow, error) {
	rows, err := q.db.QueryContext(ctx, selectDivisionPrizepool, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectDivisionPrizepoolRow
	for rows.Next() {
		var i SelectDivisionPrizepoolRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionDivisionID,
			&i.Placement,
			&i.Amount,
			&i.ID_2,
			&i.CompetitionID,
			&i.Division,
			&i.Map,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCompetitionPrizepool = `-- name: SumCompetitionPrizepool :one
select cast(coalesce(sum(amount),0) as integer) from competition_prize cp
  join competition_division cd on cp.competition_division_id = cd.id
  join competition c on cd.competition_id = c.id
  where c.id = ?
`

func (q *Queries) SumCompetitionPrizepool(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumCompetitionPrizepool, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateCompetitionPrize = `-- name: UpdateCompetitionPrize :exec
update competition_prize
  set placement = ?,
  amount = ?
  where competition_division_id = ?
`

type UpdateCompetitionPrizeParams struct {
	Placement             int64 `json:"placement"`
	Amount                int64 `json:"amount"`
	CompetitionDivisionID int64 `json:"competition_division_id"`
}

func (q *Queries) UpdateCompetitionPrize(ctx context.Context, arg UpdateCompetitionPrizeParams) error {
	_, err := q.db.ExecContext(ctx, updateCompetitionPrize, arg.Placement, arg.Amount, arg.CompetitionDivisionID)
	return err
}
