// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition.sql

package queries

import (
	"context"
	"time"
)

const insertCompetition = `-- name: InsertCompetition :one
insert into competition (class, starts_at, ends_at)
  values (?, ?, ?)
  returning id, class, starts_at, ends_at, created_at
`

type InsertCompetitionParams struct {
	Class    string    `json:"class"`
	StartsAt time.Time `json:"starts_at"`
	EndsAt   time.Time `json:"ends_at"`
}

func (q *Queries) InsertCompetition(ctx context.Context, arg InsertCompetitionParams) (Competition, error) {
	row := q.db.QueryRowContext(ctx, insertCompetition, arg.Class, arg.StartsAt, arg.EndsAt)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Class,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}
