// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition_division.sql

package queries

import (
	"context"
)

const deleteCompetitionDivision = `-- name: DeleteCompetitionDivision :one
delete from competition_division
  where id = ?
  returning id, competition_id, division, map
`

func (q *Queries) DeleteCompetitionDivision(ctx context.Context, id int64) (CompetitionDivision, error) {
	row := q.db.QueryRowContext(ctx, deleteCompetitionDivision, id)
	var i CompetitionDivision
	err := row.Scan(
		&i.ID,
		&i.CompetitionID,
		&i.Division,
		&i.Map,
	)
	return i, err
}

const insertCompetitionDivision = `-- name: InsertCompetitionDivision :exec
insert into competition_division (competition_id, division, map)
  values (?, ?, ?)
`

type InsertCompetitionDivisionParams struct {
	CompetitionID int64  `json:"competition_id"`
	Division      string `json:"division"`
	Map           string `json:"map"`
}

func (q *Queries) InsertCompetitionDivision(ctx context.Context, arg InsertCompetitionDivisionParams) error {
	_, err := q.db.ExecContext(ctx, insertCompetitionDivision, arg.CompetitionID, arg.Division, arg.Map)
	return err
}

const selectCompetitionDivision = `-- name: SelectCompetitionDivision :one
select id, competition_id, division, map from competition_division
  where id = ?
`

func (q *Queries) SelectCompetitionDivision(ctx context.Context, id int64) (CompetitionDivision, error) {
	row := q.db.QueryRowContext(ctx, selectCompetitionDivision, id)
	var i CompetitionDivision
	err := row.Scan(
		&i.ID,
		&i.CompetitionID,
		&i.Division,
		&i.Map,
	)
	return i, err
}

const selectCompetitionDivisions = `-- name: SelectCompetitionDivisions :many
select id, competition_id, division, map from competition_division
  where competition_id = ?
`

func (q *Queries) SelectCompetitionDivisions(ctx context.Context, competitionID int64) ([]CompetitionDivision, error) {
	rows, err := q.db.QueryContext(ctx, selectCompetitionDivisions, competitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionDivision
	for rows.Next() {
		var i CompetitionDivision
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionID,
			&i.Division,
			&i.Map,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetitionDivision = `-- name: UpdateCompetitionDivision :exec
update competition_division
  set map = ?
  where id = ?
`

type UpdateCompetitionDivisionParams struct {
	Map string `json:"map"`
	ID  int64  `json:"id"`
}

func (q *Queries) UpdateCompetitionDivision(ctx context.Context, arg UpdateCompetitionDivisionParams) error {
	_, err := q.db.ExecContext(ctx, updateCompetitionDivision, arg.Map, arg.ID)
	return err
}
