// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleted_record.sql

package queries

import (
	"context"
	"encoding/json"
)

const insertDeletedRecord = `-- name: InsertDeletedRecord :exec
insert into deleted_record (source_table, source_id, data)
  values (?, ?, ?)
`

type InsertDeletedRecordParams struct {
	SourceTable string          `json:"source_table"`
	SourceID    string          `json:"source_id"`
	Data        json.RawMessage `json:"data"`
}

func (q *Queries) InsertDeletedRecord(ctx context.Context, arg InsertDeletedRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertDeletedRecord, arg.SourceTable, arg.SourceID, arg.Data)
	return err
}
