// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleted_row.sql

package queries

import (
	"context"
	"encoding/json"
)

const insertDeletedRow = `-- name: InsertDeletedRow :exec
insert into deleted_row (source_table, source_id, data)
  values (?, ?, ?)
`

type InsertDeletedRowParams struct {
	SourceTable string
	SourceID    string
	Data        json.RawMessage
}

func (q *Queries) InsertDeletedRow(ctx context.Context, arg InsertDeletedRowParams) error {
	_, err := q.db.ExecContext(ctx, insertDeletedRow, arg.SourceTable, arg.SourceID, arg.Data)
	return err
}
