// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disallow_token.sql

package queries

import (
	"context"
)

const disallowToken = `-- name: DisallowToken :exec
insert into disallow_token (token_id)
  values (?)
`

func (q *Queries) DisallowToken(ctx context.Context, tokenID string) error {
	_, err := q.db.ExecContext(ctx, disallowToken, tokenID)
	return err
}

const getDisallowToken = `-- name: GetDisallowToken :one
select exists(
  select 1 from disallow_token
    where token_id = ?
)
`

func (q *Queries) GetDisallowToken(ctx context.Context, tokenID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDisallowToken, tokenID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
