// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package queries

import (
	"context"
	"time"
)

const countEventKinds = `-- name: CountEventKinds :one
select count(*) from event
  where kind = ?
`

func (q *Queries) CountEventKinds(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventKinds, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEvent = `-- name: DeleteEvent :exec
delete from event
  where id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const insertEvent = `-- name: InsertEvent :one
insert into event (kind, kind_id, class, visible_at, starts_at, ends_at)
  values (?, ?, ?, ?, ?, ?)
  returning id, kind, kind_id, class, visible_at, starts_at, ends_at, created_at
`

type InsertEventParams struct {
	Kind      string
	KindID    int64
	Class     string
	VisibleAt time.Time
	StartsAt  time.Time
	EndsAt    time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.Kind,
		arg.KindID,
		arg.Class,
		arg.VisibleAt,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.KindID,
		&i.Class,
		&i.VisibleAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const selectEvent = `-- name: SelectEvent :one
select id, kind, kind_id, class, visible_at, starts_at, ends_at, created_at from event
  where id = ?
`

func (q *Queries) SelectEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, selectEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.KindID,
		&i.Class,
		&i.VisibleAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const selectEventFromLeaderboardID = `-- name: SelectEventFromLeaderboardID :one
select e.id, e.kind, e.kind_id, e.class, e.visible_at, e.starts_at, e.ends_at, e.created_at from event e
  join leaderboard l on l.event_id = e.id
  where l.id = ?
`

func (q *Queries) SelectEventFromLeaderboardID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, selectEventFromLeaderboardID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.KindID,
		&i.Class,
		&i.VisibleAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const selectEventKind = `-- name: SelectEventKind :one
select id, kind, kind_id, class, visible_at, starts_at, ends_at, created_at from event
  where kind = ?
  and kind_id = ?
`

type SelectEventKindParams struct {
	Kind   string
	KindID int64
}

func (q *Queries) SelectEventKind(ctx context.Context, arg SelectEventKindParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, selectEventKind, arg.Kind, arg.KindID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.KindID,
		&i.Class,
		&i.VisibleAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const selectEventKinds = `-- name: SelectEventKinds :many
select id, kind, kind_id, class, visible_at, starts_at, ends_at, created_at from event
  where kind = ?
`

func (q *Queries) SelectEventKinds(ctx context.Context, kind string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, selectEventKinds, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.KindID,
			&i.Class,
			&i.VisibleAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectEventLeaderboards = `-- name: SelectEventLeaderboards :many
select event.id, event.kind, event.kind_id, event.class, event.visible_at, event.starts_at, event.ends_at, event.created_at, leaderboard.id, leaderboard.event_id, leaderboard.div, leaderboard.map from event
  join leaderboard on leaderboard.event_id = event.id
  where event.kind = ?
    and event.kind_id = ?
`

type SelectEventLeaderboardsParams struct {
	Kind   string
	KindID int64
}

type SelectEventLeaderboardsRow struct {
	Event       Event
	Leaderboard Leaderboard
}

func (q *Queries) SelectEventLeaderboards(ctx context.Context, arg SelectEventLeaderboardsParams) ([]SelectEventLeaderboardsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectEventLeaderboards, arg.Kind, arg.KindID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectEventLeaderboardsRow
	for rows.Next() {
		var i SelectEventLeaderboardsRow
		if err := rows.Scan(
			&i.Event.ID,
			&i.Event.Kind,
			&i.Event.KindID,
			&i.Event.Class,
			&i.Event.VisibleAt,
			&i.Event.StartsAt,
			&i.Event.EndsAt,
			&i.Event.CreatedAt,
			&i.Leaderboard.ID,
			&i.Leaderboard.EventID,
			&i.Leaderboard.Div,
			&i.Leaderboard.Map,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectEvents = `-- name: SelectEvents :many
select id, kind, kind_id, class, visible_at, starts_at, ends_at, created_at from event
`

func (q *Queries) SelectEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, selectEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.KindID,
			&i.Class,
			&i.VisibleAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
