// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package queries

import (
	"context"
	"database/sql"
)

const insertLeaderboard = `-- name: InsertLeaderboard :exec
insert into leaderboard (event_id, div, map)
values (?, ?, ?)
`

type InsertLeaderboardParams struct {
	EventID int64
	Div     sql.NullString
	Map     string
}

func (q *Queries) InsertLeaderboard(ctx context.Context, arg InsertLeaderboardParams) error {
	_, err := q.db.ExecContext(ctx, insertLeaderboard, arg.EventID, arg.Div, arg.Map)
	return err
}

const selectLeaderboard = `-- name: SelectLeaderboard :one
select id, event_id, div, map from leaderboard
  where id = ?
`

func (q *Queries) SelectLeaderboard(ctx context.Context, id int64) (Leaderboard, error) {
	row := q.db.QueryRowContext(ctx, selectLeaderboard, id)
	var i Leaderboard
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Div,
		&i.Map,
	)
	return i, err
}

const selectLeaderboards = `-- name: SelectLeaderboards :many
select id, event_id, div, map from leaderboard
  where event_id = ?
`

func (q *Queries) SelectLeaderboards(ctx context.Context, eventID int64) ([]Leaderboard, error) {
	rows, err := q.db.QueryContext(ctx, selectLeaderboards, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaderboard
	for rows.Next() {
		var i Leaderboard
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Div,
			&i.Map,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeaderboard = `-- name: UpdateLeaderboard :exec
update leaderboard
  set div = ?,
  map = ?
  where id = ?
`

type UpdateLeaderboardParams struct {
	Div sql.NullString
	Map string
	ID  int64
}

func (q *Queries) UpdateLeaderboard(ctx context.Context, arg UpdateLeaderboardParams) error {
	_, err := q.db.ExecContext(ctx, updateLeaderboard, arg.Div, arg.Map, arg.ID)
	return err
}
