// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: map.sql

package queries

import (
	"context"
	"database/sql"
)

const insertMap = `-- name: InsertMap :exec
insert or ignore into map (id, name, courses, bonuses, soldier_tier, demo_tier, soldier_rating, demo_rating)
  values (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMapParams struct {
	ID            int64         `json:"id"`
	Name          string        `json:"name"`
	Courses       sql.NullInt64 `json:"courses"`
	Bonuses       sql.NullInt64 `json:"bonuses"`
	SoldierTier   int64         `json:"soldier_tier"`
	DemoTier      int64         `json:"demo_tier"`
	SoldierRating int64         `json:"soldier_rating"`
	DemoRating    int64         `json:"demo_rating"`
}

func (q *Queries) InsertMap(ctx context.Context, arg InsertMapParams) error {
	_, err := q.db.ExecContext(ctx, insertMap,
		arg.ID,
		arg.Name,
		arg.Courses,
		arg.Bonuses,
		arg.SoldierTier,
		arg.DemoTier,
		arg.SoldierRating,
		arg.DemoRating,
	)
	return err
}

const selectMapNames = `-- name: SelectMapNames :many
select name from map
`

func (q *Queries) SelectMapNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, selectMapNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMaps = `-- name: SelectMaps :many
select id, name, courses, bonuses, soldier_tier, demo_tier, soldier_rating, demo_rating from map
`

func (q *Queries) SelectMaps(ctx context.Context) ([]Map, error) {
	rows, err := q.db.QueryContext(ctx, selectMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Map
	for rows.Next() {
		var i Map
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Courses,
			&i.Bonuses,
			&i.SoldierTier,
			&i.DemoTier,
			&i.SoldierRating,
			&i.DemoRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
