// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: map.sql

package queries

import (
	"context"
	"database/sql"
)

const insertMap = `-- name: InsertMap :exec
insert or ignore into map (name, courses, bonuses, soldier_tier, demo_tier, soldier_rating, demo_rating)
values (?, ?, ?, ?, ?, ?, ?)
`

type InsertMapParams struct {
	Name          string
	Courses       sql.NullInt64
	Bonuses       sql.NullInt64
	SoldierTier   int64
	DemoTier      int64
	SoldierRating int64
	DemoRating    int64
}

func (q *Queries) InsertMap(ctx context.Context, arg InsertMapParams) error {
	_, err := q.db.ExecContext(ctx, insertMap,
		arg.Name,
		arg.Courses,
		arg.Bonuses,
		arg.SoldierTier,
		arg.DemoTier,
		arg.SoldierRating,
		arg.DemoRating,
	)
	return err
}

const selectMaps = `-- name: SelectMaps :many
select name, courses, bonuses, soldier_tier, demo_tier, soldier_rating, demo_rating from map
`

func (q *Queries) SelectMaps(ctx context.Context) ([]Map, error) {
	rows, err := q.db.QueryContext(ctx, selectMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Map
	for rows.Next() {
		var i Map
		if err := rows.Scan(
			&i.Name,
			&i.Courses,
			&i.Bonuses,
			&i.SoldierTier,
			&i.DemoTier,
			&i.SoldierRating,
			&i.DemoRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
