// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Bounty struct {
	ID            int64           `json:"id"`
	CompetitionID int64           `json:"competition_id"`
	Map           string          `json:"map"`
	Type          string          `json:"type"`
	Time          sql.NullFloat64 `json:"time"`
}

type Competition struct {
	ID        int64     `json:"id"`
	Class     string    `json:"class"`
	StartsAt  time.Time `json:"starts_at"`
	EndsAt    time.Time `json:"ends_at"`
	CreatedAt time.Time `json:"created_at"`
}

type CompetitionDivision struct {
	ID            int64  `json:"id"`
	CompetitionID int64  `json:"competition_id"`
	Division      string `json:"division"`
	Map           string `json:"map"`
}

type CompetitionPrize struct {
	ID            int64 `json:"id"`
	CompetitionID int64 `json:"competition_id"`
	Placement     int64 `json:"placement"`
	Amount        int64 `json:"amount"`
}

type CompetitionResult struct {
	CompetitionID int64     `json:"competition_id"`
	PlayerID      int64     `json:"player_id"`
	Placement     int64     `json:"placement"`
	Points        int64     `json:"points"`
	CreatedAt     time.Time `json:"created_at"`
}

type DeletedRecord struct {
	ID          int64           `json:"id"`
	SourceTable string          `json:"source_table"`
	SourceID    string          `json:"source_id"`
	Data        json.RawMessage `json:"data"`
	DeletedAt   time.Time       `json:"deleted_at"`
}

type Monthly struct {
	ID            int64 `json:"id"`
	CompetitionID int64 `json:"competition_id"`
}

type Motw struct {
	ID            int64 `json:"id"`
	CompetitionID int64 `json:"competition_id"`
}

type Player struct {
	ID              int64          `json:"id"`
	Role            string         `json:"role"`
	SteamID         string         `json:"steam_id"`
	SteamPfpID      string         `json:"steam_pfp_id"`
	SteamTradeToken sql.NullString `json:"steam_trade_token"`
	TempusID        sql.NullInt64  `json:"tempus_id"`
	DiscordID       sql.NullString `json:"discord_id"`
	DisplayName     string         `json:"display_name"`
	SoldierDivision sql.NullString `json:"soldier_division"`
	DemoDivision    sql.NullString `json:"demo_division"`
	PreferredClass  string         `json:"preferred_class"`
	CreatedAt       time.Time      `json:"created_at"`
}

type PlayerPoint struct {
	ID            int64 `json:"id"`
	PlayerID      int64 `json:"player_id"`
	SoldierPoints int64 `json:"soldier_points"`
	DemoPoints    int64 `json:"demo_points"`
}

type PlayerTime struct {
	ID            int64     `json:"id"`
	CompetitionID int64     `json:"competition_id"`
	PlayerID      int64     `json:"player_id"`
	RunTime       float64   `json:"run_time"`
	Verified      bool      `json:"verified"`
	CreatedAt     time.Time `json:"created_at"`
}

type Quest struct {
	ID              int64           `json:"id"`
	CompetitionID   int64           `json:"competition_id"`
	Type            string          `json:"type"`
	Time            sql.NullFloat64 `json:"time"`
	CompletionLimit string          `json:"completion_limit"`
}
