// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type DeletedRow struct {
	ID          int64
	SourceTable string
	SourceID    string
	Data        json.RawMessage
	DeletedAt   time.Time
}

type DisallowToken struct {
	TokenID   string
	CreatedAt time.Time
}

type Event struct {
	ID        int64
	Kind      string
	KindID    int64
	Class     string
	VisibleAt time.Time
	StartsAt  time.Time
	EndsAt    time.Time
	CreatedAt time.Time
}

type Leaderboard struct {
	ID      int64
	EventID int64
	Div     sql.NullString
	Map     string
}

type Map struct {
	Name          string
	Courses       sql.NullInt64
	Bonuses       sql.NullInt64
	SoldierTier   int64
	DemoTier      int64
	SoldierRating int64
	DemoRating    int64
}

type MotwTimeslot struct {
	ID       int64
	StartsAt time.Time
}

type OpenidNonce struct {
	ID          int64
	Endpoint    string
	NonceTime   time.Time
	NonceString string
	CreatedAt   time.Time
}

type Player struct {
	ID           string
	Role         string
	Alias        sql.NullString
	SoldierDiv   sql.NullString
	DemoDiv      sql.NullString
	AvatarUrl    sql.NullString
	TradeToken   sql.NullString
	TempusID     sql.NullInt64
	Country      sql.NullString
	CountryCode  sql.NullString
	ClassPref    string
	MapPref      sql.NullString
	LauncherPref sql.NullString
	CreatedAt    time.Time
}

type PlayerMotwTimeslot struct {
	TimeslotID int64
	PlayerID   string
}

type Request struct {
	ID        int64
	PlayerID  string
	Kind      string
	Content   string
	Pending   bool
	CreatedAt time.Time
}

type Session struct {
	ID        int64
	PlayerID  string
	TokenID   string
	CreatedAt time.Time
}

type Time struct {
	ID            int64
	LeaderboardID int64
	PlayerID      string
	TempusTimeID  sql.NullInt64
	Duration      float64
	Verified      bool
	CreatedAt     time.Time
}
