// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monthly.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const insertMonthly = `-- name: InsertMonthly :exec
insert into monthly (competition_id)
  values (?)
`

func (q *Queries) InsertMonthly(ctx context.Context, competitionID int64) error {
	_, err := q.db.ExecContext(ctx, insertMonthly, competitionID)
	return err
}

const selectAllMonthly = `-- name: SelectAllMonthly :many
select m.id, competition_id, c.id, type, class, prizepool, starts_at, ends_at, visible_at, complete, created_at from monthly m
  join competition c on m.competition_id = c.id
`

type SelectAllMonthlyRow struct {
	ID            int64         `json:"id"`
	CompetitionID int64         `json:"competition_id"`
	ID_2          int64         `json:"id_2"`
	Type          string        `json:"type"`
	Class         string        `json:"class"`
	Prizepool     sql.NullInt64 `json:"prizepool"`
	StartsAt      time.Time     `json:"starts_at"`
	EndsAt        time.Time     `json:"ends_at"`
	VisibleAt     time.Time     `json:"visible_at"`
	Complete      bool          `json:"complete"`
	CreatedAt     time.Time     `json:"created_at"`
}

func (q *Queries) SelectAllMonthly(ctx context.Context) ([]SelectAllMonthlyRow, error) {
	rows, err := q.db.QueryContext(ctx, selectAllMonthly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAllMonthlyRow
	for rows.Next() {
		var i SelectAllMonthlyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionID,
			&i.ID_2,
			&i.Type,
			&i.Class,
			&i.Prizepool,
			&i.StartsAt,
			&i.EndsAt,
			&i.VisibleAt,
			&i.Complete,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMonthly = `-- name: SelectMonthly :one
select m.id, competition_id, c.id, type, class, prizepool, starts_at, ends_at, visible_at, complete, created_at from monthly m
  join competition c on m.competition_id = c.id
  where m.id = ?
`

type SelectMonthlyRow struct {
	ID            int64         `json:"id"`
	CompetitionID int64         `json:"competition_id"`
	ID_2          int64         `json:"id_2"`
	Type          string        `json:"type"`
	Class         string        `json:"class"`
	Prizepool     sql.NullInt64 `json:"prizepool"`
	StartsAt      time.Time     `json:"starts_at"`
	EndsAt        time.Time     `json:"ends_at"`
	VisibleAt     time.Time     `json:"visible_at"`
	Complete      bool          `json:"complete"`
	CreatedAt     time.Time     `json:"created_at"`
}

func (q *Queries) SelectMonthly(ctx context.Context, id int64) (SelectMonthlyRow, error) {
	row := q.db.QueryRowContext(ctx, selectMonthly, id)
	var i SelectMonthlyRow
	err := row.Scan(
		&i.ID,
		&i.CompetitionID,
		&i.ID_2,
		&i.Type,
		&i.Class,
		&i.Prizepool,
		&i.StartsAt,
		&i.EndsAt,
		&i.VisibleAt,
		&i.Complete,
		&i.CreatedAt,
	)
	return i, err
}

const selectMonthlyCompetitionID = `-- name: SelectMonthlyCompetitionID :one
select competition_id from monthly m
  where m.id = ?
`

func (q *Queries) SelectMonthlyCompetitionID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectMonthlyCompetitionID, id)
	var competition_id int64
	err := row.Scan(&competition_id)
	return competition_id, err
}
