// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_request.sql

package queries

import (
	"context"
	"database/sql"
)

const checkPendingPlayerRequest = `-- name: CheckPendingPlayerRequest :one
select exists (
  select 1
  from player_request
  where player_id = ? and type = ? and pending = true)
`

type CheckPendingPlayerRequestParams struct {
	PlayerID string `json:"player_id"`
	Type     string `json:"type"`
}

func (q *Queries) CheckPendingPlayerRequest(ctx context.Context, arg CheckPendingPlayerRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPendingPlayerRequest, arg.PlayerID, arg.Type)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllPlayerRequests = `-- name: GetAllPlayerRequests :many
select id, player_id, type, content, pending, accepted, created_at from player_request
`

func (q *Queries) GetAllPlayerRequests(ctx context.Context) ([]PlayerRequest, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayerRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRequest
	for rows.Next() {
		var i PlayerRequest
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Type,
			&i.Content,
			&i.Pending,
			&i.Accepted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingPlayerRequestsForPlayer = `-- name: GetPendingPlayerRequestsForPlayer :many
select id, player_id, type, content, pending, accepted, created_at from player_request
where player_id = ? and pending = true
`

// may be unnecessary
func (q *Queries) GetPendingPlayerRequestsForPlayer(ctx context.Context, playerID string) ([]PlayerRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingPlayerRequestsForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRequest
	for rows.Next() {
		var i PlayerRequest
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Type,
			&i.Content,
			&i.Pending,
			&i.Accepted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlayerRequest = `-- name: InsertPlayerRequest :exec
insert into player_request (player_id, type, content)
values (?, ?, ?)
`

type InsertPlayerRequestParams struct {
	PlayerID string         `json:"player_id"`
	Type     string         `json:"type"`
	Content  sql.NullString `json:"content"`
}

func (q *Queries) InsertPlayerRequest(ctx context.Context, arg InsertPlayerRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerRequest, arg.PlayerID, arg.Type, arg.Content)
	return err
}
