// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package queries

import (
	"context"
	"database/sql"
)

const insertPlayer = `-- name: InsertPlayer :one
insert into player (id)
  values (?)
  on conflict do update
    set id = id
  returning id, role, alias, soldier_div, demo_div, avatar_url, trade_token, tempus_id, country, country_code, class_pref, map_pref, launcher_pref, created_at
`

func (q *Queries) InsertPlayer(ctx context.Context, id string) (Player, error) {
	row := q.db.QueryRowContext(ctx, insertPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Alias,
		&i.SoldierDiv,
		&i.DemoDiv,
		&i.AvatarUrl,
		&i.TradeToken,
		&i.TempusID,
		&i.Country,
		&i.CountryCode,
		&i.ClassPref,
		&i.MapPref,
		&i.LauncherPref,
		&i.CreatedAt,
	)
	return i, err
}

const selectPlayer = `-- name: SelectPlayer :one
select id, role, alias, soldier_div, demo_div, avatar_url, trade_token, tempus_id, country, country_code, class_pref, map_pref, launcher_pref, created_at from player
  where id = ?
`

func (q *Queries) SelectPlayer(ctx context.Context, id string) (Player, error) {
	row := q.db.QueryRowContext(ctx, selectPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Alias,
		&i.SoldierDiv,
		&i.DemoDiv,
		&i.AvatarUrl,
		&i.TradeToken,
		&i.TempusID,
		&i.Country,
		&i.CountryCode,
		&i.ClassPref,
		&i.MapPref,
		&i.LauncherPref,
		&i.CreatedAt,
	)
	return i, err
}

const selectPlayers = `-- name: SelectPlayers :many
select id, role, alias, soldier_div, demo_div, avatar_url, trade_token, tempus_id, country, country_code, class_pref, map_pref, launcher_pref, created_at from player
`

func (q *Queries) SelectPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, selectPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Alias,
			&i.SoldierDiv,
			&i.DemoDiv,
			&i.AvatarUrl,
			&i.TradeToken,
			&i.TempusID,
			&i.Country,
			&i.CountryCode,
			&i.ClassPref,
			&i.MapPref,
			&i.LauncherPref,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerAlias = `-- name: UpdatePlayerAlias :exec
update player
  set alias = ?
  where id = ?
`

type UpdatePlayerAliasParams struct {
	Alias sql.NullString
	ID    string
}

func (q *Queries) UpdatePlayerAlias(ctx context.Context, arg UpdatePlayerAliasParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerAlias, arg.Alias, arg.ID)
	return err
}

const updatePlayerAvatarURL = `-- name: UpdatePlayerAvatarURL :exec
update player
  set avatar_url = ?
  where id = ?
`

type UpdatePlayerAvatarURLParams struct {
	AvatarUrl sql.NullString
	ID        string
}

func (q *Queries) UpdatePlayerAvatarURL(ctx context.Context, arg UpdatePlayerAvatarURLParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerAvatarURL, arg.AvatarUrl, arg.ID)
	return err
}

const updatePlayerClassPref = `-- name: UpdatePlayerClassPref :exec
update player
  set class_pref = ?
  where id = ?
`

type UpdatePlayerClassPrefParams struct {
	ClassPref string
	ID        string
}

func (q *Queries) UpdatePlayerClassPref(ctx context.Context, arg UpdatePlayerClassPrefParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerClassPref, arg.ClassPref, arg.ID)
	return err
}

const updatePlayerDemoDiv = `-- name: UpdatePlayerDemoDiv :exec
update player
  set demo_div = ?
  where id = ?
`

type UpdatePlayerDemoDivParams struct {
	DemoDiv sql.NullString
	ID      string
}

func (q *Queries) UpdatePlayerDemoDiv(ctx context.Context, arg UpdatePlayerDemoDivParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerDemoDiv, arg.DemoDiv, arg.ID)
	return err
}

const updatePlayerRole = `-- name: UpdatePlayerRole :exec
update player
  set role = ?
  where id = ?
`

type UpdatePlayerRoleParams struct {
	Role string
	ID   string
}

func (q *Queries) UpdatePlayerRole(ctx context.Context, arg UpdatePlayerRoleParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerRole, arg.Role, arg.ID)
	return err
}

const updatePlayerSoldierDiv = `-- name: UpdatePlayerSoldierDiv :exec
update player
  set soldier_div = ?
  where id = ?
`

type UpdatePlayerSoldierDivParams struct {
	SoldierDiv sql.NullString
	ID         string
}

func (q *Queries) UpdatePlayerSoldierDiv(ctx context.Context, arg UpdatePlayerSoldierDivParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerSoldierDiv, arg.SoldierDiv, arg.ID)
	return err
}

const updatePlayerTempusInfo = `-- name: UpdatePlayerTempusInfo :exec
update player
  set tempus_id = ?,
    country = ?,
    country_code = ?
  where id = ?
`

type UpdatePlayerTempusInfoParams struct {
	TempusID    sql.NullInt64
	Country     sql.NullString
	CountryCode sql.NullString
	ID          string
}

func (q *Queries) UpdatePlayerTempusInfo(ctx context.Context, arg UpdatePlayerTempusInfoParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerTempusInfo,
		arg.TempusID,
		arg.Country,
		arg.CountryCode,
		arg.ID,
	)
	return err
}

const updatePlayerTradeToken = `-- name: UpdatePlayerTradeToken :exec
update player
  set trade_token = ?
  where id = ?
`

type UpdatePlayerTradeTokenParams struct {
	TradeToken sql.NullString
	ID         string
}

func (q *Queries) UpdatePlayerTradeToken(ctx context.Context, arg UpdatePlayerTradeTokenParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerTradeToken, arg.TradeToken, arg.ID)
	return err
}
