// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package queries

import (
	"context"
)

const insertPlayer = `-- name: InsertPlayer :one
insert into player (steam_id64)
  values (?)
  on conflict do update set steam_id64 = steam_id64
  returning id, role, steam_id64, steam_id3, steam_trade_token, steam_pfp_id, tempus_id, discord_id, display_name, soldier_division, demo_division, preferred_class, created_at
`

func (q *Queries) InsertPlayer(ctx context.Context, steamId64 string) (Player, error) {
	row := q.db.QueryRowContext(ctx, insertPlayer, steamId64)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.SteamId64,
		&i.SteamId3,
		&i.SteamTradeToken,
		&i.SteamPfpID,
		&i.TempusID,
		&i.DiscordID,
		&i.DisplayName,
		&i.SoldierDivision,
		&i.DemoDivision,
		&i.PreferredClass,
		&i.CreatedAt,
	)
	return i, err
}

const selectPlayer = `-- name: SelectPlayer :one
select id, role, steam_id64, steam_id3, steam_trade_token, steam_pfp_id, tempus_id, discord_id, display_name, soldier_division, demo_division, preferred_class, created_at from player
  where id = ?
`

func (q *Queries) SelectPlayer(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, selectPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.SteamId64,
		&i.SteamId3,
		&i.SteamTradeToken,
		&i.SteamPfpID,
		&i.TempusID,
		&i.DiscordID,
		&i.DisplayName,
		&i.SoldierDivision,
		&i.DemoDivision,
		&i.PreferredClass,
		&i.CreatedAt,
	)
	return i, err
}
