// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_request.sql

package queries

import (
	"context"
	"database/sql"
)

const getAllPendingPlayerRequests = `-- name: GetAllPendingPlayerRequests :many
select id, player_id, type, content, pending, accepted, created_at from player_request
  where id = ? and pending = true
`

func (q *Queries) GetAllPendingPlayerRequests(ctx context.Context, id int64) ([]PlayerRequest, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingPlayerRequests, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRequest
	for rows.Next() {
		var i PlayerRequest
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Type,
			&i.Content,
			&i.Pending,
			&i.Accepted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlayerRequests = `-- name: GetAllPlayerRequests :many
select id, player_id, type, content, pending, accepted, created_at from player_request
`

func (q *Queries) GetAllPlayerRequests(ctx context.Context) ([]PlayerRequest, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayerRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRequest
	for rows.Next() {
		var i PlayerRequest
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Type,
			&i.Content,
			&i.Pending,
			&i.Accepted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlayerRequest = `-- name: InsertPlayerRequest :exec
insert into player_request (player_id, type, content)
  select player.id, ?, ? from player
  where player.steam_id64 = ?
`

type InsertPlayerRequestParams struct {
	Type      string         `json:"type"`
	Content   sql.NullString `json:"content"`
	SteamId64 string         `json:"steam_id64"`
}

func (q *Queries) InsertPlayerRequest(ctx context.Context, arg InsertPlayerRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerRequest, arg.Type, arg.Content, arg.SteamId64)
	return err
}
