// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_time.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const deletePlayerTime = `-- name: DeletePlayerTime :one
delete from player_time
  where id = ?
  returning id, player_id, competition_division_id, tempus_time_id, run_time, verified, created_at
`

func (q *Queries) DeletePlayerTime(ctx context.Context, id int64) (PlayerTime, error) {
	row := q.db.QueryRowContext(ctx, deletePlayerTime, id)
	var i PlayerTime
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.CompetitionDivisionID,
		&i.TempusTimeID,
		&i.RunTime,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlayerTime = `-- name: InsertPlayerTime :exec
insert into player_time (player_id, competition_division_id, run_time, verified)
  values (?, ?, ?, ?)
`

type InsertPlayerTimeParams struct {
	PlayerID              string  `json:"player_id"`
	CompetitionDivisionID int64   `json:"competition_division_id"`
	RunTime               float64 `json:"run_time"`
	Verified              bool    `json:"verified"`
}

func (q *Queries) InsertPlayerTime(ctx context.Context, arg InsertPlayerTimeParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerTime,
		arg.PlayerID,
		arg.CompetitionDivisionID,
		arg.RunTime,
		arg.Verified,
	)
	return err
}

const selectCompetitionDivisionPRTimes = `-- name: SelectCompetitionDivisionPRTimes :many
select pt.id, pt.player_id, pt.competition_division_id, min(run_time) as run_time, pt.verified, pt.created_at,
p.steam_avatar_url, p.display_name
from player_time pt
  join player p on pt.player_id = p.id
    where pt.competition_division_id = ?
  group by p.id
  order by run_time
`

type SelectCompetitionDivisionPRTimesRow struct {
	ID                    int64          `json:"id"`
	PlayerID              string         `json:"player_id"`
	CompetitionDivisionID int64          `json:"competition_division_id"`
	RunTime               interface{}    `json:"run_time"`
	Verified              bool           `json:"verified"`
	CreatedAt             time.Time      `json:"created_at"`
	SteamAvatarUrl        sql.NullString `json:"steam_avatar_url"`
	DisplayName           sql.NullString `json:"display_name"`
}

func (q *Queries) SelectCompetitionDivisionPRTimes(ctx context.Context, competitionDivisionID int64) ([]SelectCompetitionDivisionPRTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectCompetitionDivisionPRTimes, competitionDivisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectCompetitionDivisionPRTimesRow
	for rows.Next() {
		var i SelectCompetitionDivisionPRTimesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.CompetitionDivisionID,
			&i.RunTime,
			&i.Verified,
			&i.CreatedAt,
			&i.SteamAvatarUrl,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyPlayerTime = `-- name: VerifyPlayerTime :exec
update player_time
  set verified = true
  where id = ?
`

func (q *Queries) VerifyPlayerTime(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, verifyPlayerTime, id)
	return err
}
