// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_points.sql

package queries

import (
	"context"
)

const insertPlayerPoints = `-- name: InsertPlayerPoints :exec
insert or ignore into player_points (class, player_id)
values (?, ?)
`

type InsertPlayerPointsParams struct {
	Class    string `json:"class"`
	PlayerID int64  `json:"player_id"`
}

func (q *Queries) InsertPlayerPoints(ctx context.Context, arg InsertPlayerPointsParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerPoints, arg.Class, arg.PlayerID)
	return err
}

const selectPlayerPoints = `-- name: SelectPlayerPoints :one
select id, class, player_id, total, last_9_motw, last_3_monthly from player_points
where player_id = ?
and class = ?
`

type SelectPlayerPointsParams struct {
	PlayerID int64  `json:"player_id"`
	Class    string `json:"class"`
}

func (q *Queries) SelectPlayerPoints(ctx context.Context, arg SelectPlayerPointsParams) (PlayerPoint, error) {
	row := q.db.QueryRowContext(ctx, selectPlayerPoints, arg.PlayerID, arg.Class)
	var i PlayerPoint
	err := row.Scan(
		&i.ID,
		&i.Class,
		&i.PlayerID,
		&i.Total,
		&i.Last9Motw,
		&i.Last3Monthly,
	)
	return i, err
}
