// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prize.sql

package queries

import (
	"context"
	"database/sql"
)

const deletePrizepool = `-- name: DeletePrizepool :exec
delete from prize
  where leaderboard_id = ?
`

func (q *Queries) DeletePrizepool(ctx context.Context, leaderboardID int64) error {
	_, err := q.db.ExecContext(ctx, deletePrizepool, leaderboardID)
	return err
}

const insertPrize = `-- name: InsertPrize :exec
insert into prize (leaderboard_id, position, keys)
  values (?, ?, ?)
`

type InsertPrizeParams struct {
	LeaderboardID int64
	Position      int64
	Keys          int64
}

func (q *Queries) InsertPrize(ctx context.Context, arg InsertPrizeParams) error {
	_, err := q.db.ExecContext(ctx, insertPrize, arg.LeaderboardID, arg.Position, arg.Keys)
	return err
}

const selectPrize = `-- name: SelectPrize :one
select leaderboard_id, player_id, position, keys from prize
  where leaderboard_id = ?
  and player_id = ?
`

type SelectPrizeParams struct {
	LeaderboardID int64
	PlayerID      sql.NullString
}

func (q *Queries) SelectPrize(ctx context.Context, arg SelectPrizeParams) (Prize, error) {
	row := q.db.QueryRowContext(ctx, selectPrize, arg.LeaderboardID, arg.PlayerID)
	var i Prize
	err := row.Scan(
		&i.LeaderboardID,
		&i.PlayerID,
		&i.Position,
		&i.Keys,
	)
	return i, err
}

const selectPrizepool = `-- name: SelectPrizepool :many
select leaderboard_id, player_id, position, keys from prize
  where leaderboard_id = ?
`

func (q *Queries) SelectPrizepool(ctx context.Context, leaderboardID int64) ([]Prize, error) {
	rows, err := q.db.QueryContext(ctx, selectPrizepool, leaderboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prize
	for rows.Next() {
		var i Prize
		if err := rows.Scan(
			&i.LeaderboardID,
			&i.PlayerID,
			&i.Position,
			&i.Keys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPrizepoolTotal = `-- name: SelectPrizepoolTotal :one
select cast(coalesce(sum(p.keys), 0) as integer) from prize p
  join leaderboard l on p.leaderboard_id = l.id
  join event e on l.event_id = e.id
  where e.id = ?
`

func (q *Queries) SelectPrizepoolTotal(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectPrizepoolTotal, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updatePrize = `-- name: UpdatePrize :exec
update prize
  set player_id = ?
  where leaderboard_id = ?
  and position = ?
`

type UpdatePrizeParams struct {
	PlayerID      sql.NullString
	LeaderboardID int64
	Position      int64
}

func (q *Queries) UpdatePrize(ctx context.Context, arg UpdatePrizeParams) error {
	_, err := q.db.ExecContext(ctx, updatePrize, arg.PlayerID, arg.LeaderboardID, arg.Position)
	return err
}
