// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request.sql

package queries

import (
	"context"
)

const checkPendingRequestExists = `-- name: CheckPendingRequestExists :one
select exists (
  select 1
  from request
  where player_id = ? and kind = ? and pending = true)
`

type CheckPendingRequestExistsParams struct {
	PlayerID string
	Kind     string
}

func (q *Queries) CheckPendingRequestExists(ctx context.Context, arg CheckPendingRequestExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPendingRequestExists, arg.PlayerID, arg.Kind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertRequest = `-- name: InsertRequest :exec
insert into request (player_id, kind, content)
  values (?, ?, ?)
`

type InsertRequestParams struct {
	PlayerID string
	Kind     string
	Content  string
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertRequest, arg.PlayerID, arg.Kind, arg.Content)
	return err
}

const resolveRequest = `-- name: ResolveRequest :exec
update request
  set pending = false
  where id = ?
`

func (q *Queries) ResolveRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resolveRequest, id)
	return err
}

const selectPendingRequests = `-- name: SelectPendingRequests :many
select id, player_id, kind, content, pending, created_at from request
  where pending = true
`

func (q *Queries) SelectPendingRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, selectPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Kind,
			&i.Content,
			&i.Pending,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPlayerRequests = `-- name: SelectPlayerRequests :many
select id, player_id, kind, content, pending, created_at from request
  where player_id = ?
`

func (q *Queries) SelectPlayerRequests(ctx context.Context, playerID string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, selectPlayerRequests, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Kind,
			&i.Content,
			&i.Pending,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
