// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package queries

import (
	"context"
)

const addSession = `-- name: AddSession :one
insert into session (player_id, token_id)
  values (?, ?)
  returning id, player_id, token_id, created_at
`

type AddSessionParams struct {
	PlayerID string `json:"player_id"`
	TokenID  string `json:"token_id"`
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, addSession, arg.PlayerID, arg.TokenID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}
