// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package queries

import (
	"context"
)

const addSession = `-- name: AddSession :one
insert into session (player_id, token_id)
  select player.id, ? from player
  where steam_id64 = ?
  returning id, player_id, token_id, created_at
`

type AddSessionParams struct {
	TokenID   string `json:"token_id"`
	SteamId64 string `json:"steam_id64"`
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, addSession, arg.TokenID, arg.SteamId64)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}
