// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package queries

import (
	"context"
)

const insertSession = `-- name: InsertSession :one
insert into session (player_id, token_id)
  values (?, ?)
  returning id, player_id, token_id, created_at
`

type InsertSessionParams struct {
	PlayerID string
	TokenID  string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession, arg.PlayerID, arg.TokenID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}
