// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: time.sql

package queries

import (
	"context"
	"database/sql"
)

const countPlayerTimesFromLeaderboard = `-- name: CountPlayerTimesFromLeaderboard :one
select count(*) from time
  where leaderboard_id = ?
  and player_id = ?
`

type CountPlayerTimesFromLeaderboardParams struct {
	LeaderboardID int64
	PlayerID      string
}

func (q *Queries) CountPlayerTimesFromLeaderboard(ctx context.Context, arg CountPlayerTimesFromLeaderboardParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayerTimesFromLeaderboard, arg.LeaderboardID, arg.PlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTime = `-- name: DeleteTime :exec
delete from time
  where id = ?
`

func (q *Queries) DeleteTime(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTime, id)
	return err
}

const insertTime = `-- name: InsertTime :exec
insert into time (leaderboard_id, player_id, tempus_time_id, duration, verified)
  values (?, ?, ?, ?, ?)
`

type InsertTimeParams struct {
	LeaderboardID int64
	PlayerID      string
	TempusTimeID  sql.NullInt64
	Duration      float64
	Verified      bool
}

func (q *Queries) InsertTime(ctx context.Context, arg InsertTimeParams) error {
	_, err := q.db.ExecContext(ctx, insertTime,
		arg.LeaderboardID,
		arg.PlayerID,
		arg.TempusTimeID,
		arg.Duration,
		arg.Verified,
	)
	return err
}

const selectPRTime = `-- name: SelectPRTime :one
select cast(min(duration) as float) as duration from time
  where leaderboard_id = ?
  and player_id = ?
`

type SelectPRTimeParams struct {
	LeaderboardID int64
	PlayerID      string
}

func (q *Queries) SelectPRTime(ctx context.Context, arg SelectPRTimeParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, selectPRTime, arg.LeaderboardID, arg.PlayerID)
	var duration float64
	err := row.Scan(&duration)
	return duration, err
}

const selectTime = `-- name: SelectTime :one
select id, leaderboard_id, player_id, tempus_time_id, duration, verified, created_at from time
  where id = ?
`

func (q *Queries) SelectTime(ctx context.Context, id int64) (Time, error) {
	row := q.db.QueryRowContext(ctx, selectTime, id)
	var i Time
	err := row.Scan(
		&i.ID,
		&i.LeaderboardID,
		&i.PlayerID,
		&i.TempusTimeID,
		&i.Duration,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const selectTimeExists = `-- name: SelectTimeExists :one
select exists(
  select 1 from time
  where leaderboard_id = ?
  and player_id = ?
  and duration = ?
)
`

type SelectTimeExistsParams struct {
	LeaderboardID int64
	PlayerID      string
	Duration      float64
}

func (q *Queries) SelectTimeExists(ctx context.Context, arg SelectTimeExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectTimeExists, arg.LeaderboardID, arg.PlayerID, arg.Duration)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const selectTimesFromLeaderboard = `-- name: SelectTimesFromLeaderboard :many
select id, leaderboard_id, player_id, tempus_time_id, duration, verified, created_at from time
where leaderboard_id = ?
`

func (q *Queries) SelectTimesFromLeaderboard(ctx context.Context, leaderboardID int64) ([]Time, error) {
	rows, err := q.db.QueryContext(ctx, selectTimesFromLeaderboard, leaderboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Time
	for rows.Next() {
		var i Time
		if err := rows.Scan(
			&i.ID,
			&i.LeaderboardID,
			&i.PlayerID,
			&i.TempusTimeID,
			&i.Duration,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyTime = `-- name: VerifyTime :exec
update time
  set verified = true
  where id = ?
`

func (q *Queries) VerifyTime(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, verifyTime, id)
	return err
}
