// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeslot.sql

package queries

import (
	"context"
	"time"
)

const selectPlayerTimeslot = `-- name: SelectPlayerTimeslot :one
select motw_timeslot.id, motw_timeslot.starts_at, player_motw_timeslot.timeslot_id, player_motw_timeslot.player_id from player_motw_timeslot
  join motw_timeslot on player_motw_timeslot.timeslot_id = motw_timeslot.id
where player_motw_timeslot.player_id = ?
`

type SelectPlayerTimeslotRow struct {
	MotwTimeslot       MotwTimeslot
	PlayerMotwTimeslot PlayerMotwTimeslot
}

func (q *Queries) SelectPlayerTimeslot(ctx context.Context, playerID string) (SelectPlayerTimeslotRow, error) {
	row := q.db.QueryRowContext(ctx, selectPlayerTimeslot, playerID)
	var i SelectPlayerTimeslotRow
	err := row.Scan(
		&i.MotwTimeslot.ID,
		&i.MotwTimeslot.StartsAt,
		&i.PlayerMotwTimeslot.TimeslotID,
		&i.PlayerMotwTimeslot.PlayerID,
	)
	return i, err
}

const selectTimeslots = `-- name: SelectTimeslots :many
select id, starts_at from motw_timeslot
`

func (q *Queries) SelectTimeslots(ctx context.Context) ([]MotwTimeslot, error) {
	rows, err := q.db.QueryContext(ctx, selectTimeslots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MotwTimeslot
	for rows.Next() {
		var i MotwTimeslot
		if err := rows.Scan(&i.ID, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerTimeslot = `-- name: UpdatePlayerTimeslot :exec
update player_motw_timeslot
  set timeslot_id = ?
  where player_id = ?
`

type UpdatePlayerTimeslotParams struct {
	TimeslotID int64
	PlayerID   string
}

func (q *Queries) UpdatePlayerTimeslot(ctx context.Context, arg UpdatePlayerTimeslotParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerTimeslot, arg.TimeslotID, arg.PlayerID)
	return err
}

const upsertTimeslot = `-- name: UpsertTimeslot :exec
insert into motw_timeslot (id, starts_at)
  values (?, ?)
  on conflict do update
    set starts_at = excluded.starts_at
`

type UpsertTimeslotParams struct {
	ID       int64
	StartsAt time.Time
}

func (q *Queries) UpsertTimeslot(ctx context.Context, arg UpsertTimeslotParams) error {
	_, err := q.db.ExecContext(ctx, upsertTimeslot, arg.ID, arg.StartsAt)
	return err
}
