// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: time.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countPlayerTimesFromLeaderboard = `-- name: CountPlayerTimesFromLeaderboard :one
select count(*) from time
  where leaderboard_id = ?
  and player_id = ?
`

type CountPlayerTimesFromLeaderboardParams struct {
	LeaderboardID int64
	PlayerID      string
}

func (q *Queries) CountPlayerTimesFromLeaderboard(ctx context.Context, arg CountPlayerTimesFromLeaderboardParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayerTimesFromLeaderboard, arg.LeaderboardID, arg.PlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTime = `-- name: DeleteTime :exec
delete from time
  where id = ?
`

func (q *Queries) DeleteTime(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTime, id)
	return err
}

const insertTime = `-- name: InsertTime :exec
insert into time (leaderboard_id, player_id, tempus_time_id, duration, verified)
  values (?, ?, ?, ?, ?)
`

type InsertTimeParams struct {
	LeaderboardID int64
	PlayerID      string
	TempusTimeID  sql.NullInt64
	Duration      float64
	Verified      bool
}

func (q *Queries) InsertTime(ctx context.Context, arg InsertTimeParams) error {
	_, err := q.db.ExecContext(ctx, insertTime,
		arg.LeaderboardID,
		arg.PlayerID,
		arg.TempusTimeID,
		arg.Duration,
		arg.Verified,
	)
	return err
}

const selectPRTimesFromLeaderboard = `-- name: SelectPRTimesFromLeaderboard :many
select time.id, time.leaderboard_id, time.player_id, time.tempus_time_id, time.duration, time.verified, time.created_at, player.id, player.role, player.alias, player.soldier_div, player.demo_div, player.avatar_url, player.trade_token, player.tempus_id, player.country, player.country_code, player.class_pref, player.map_pref, player.launcher_pref, player.created_at, cast(rank() over (order by duration) as integer) time_position from time
  join player on time.player_id = player.id
  where time.leaderboard_id = ?
  group by player.id
`

type SelectPRTimesFromLeaderboardRow struct {
	Time         Time
	Player       Player
	TimePosition int64
}

func (q *Queries) SelectPRTimesFromLeaderboard(ctx context.Context, leaderboardID int64) ([]SelectPRTimesFromLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, selectPRTimesFromLeaderboard, leaderboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPRTimesFromLeaderboardRow
	for rows.Next() {
		var i SelectPRTimesFromLeaderboardRow
		if err := rows.Scan(
			&i.Time.ID,
			&i.Time.LeaderboardID,
			&i.Time.PlayerID,
			&i.Time.TempusTimeID,
			&i.Time.Duration,
			&i.Time.Verified,
			&i.Time.CreatedAt,
			&i.Player.ID,
			&i.Player.Role,
			&i.Player.Alias,
			&i.Player.SoldierDiv,
			&i.Player.DemoDiv,
			&i.Player.AvatarUrl,
			&i.Player.TradeToken,
			&i.Player.TempusID,
			&i.Player.Country,
			&i.Player.CountryCode,
			&i.Player.ClassPref,
			&i.Player.MapPref,
			&i.Player.LauncherPref,
			&i.Player.CreatedAt,
			&i.TimePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTime = `-- name: SelectTime :one
select id, leaderboard_id, player_id, tempus_time_id, duration, verified, created_at from time
  where id = ?
`

func (q *Queries) SelectTime(ctx context.Context, id int64) (Time, error) {
	row := q.db.QueryRowContext(ctx, selectTime, id)
	var i Time
	err := row.Scan(
		&i.ID,
		&i.LeaderboardID,
		&i.PlayerID,
		&i.TempusTimeID,
		&i.Duration,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const selectTimeExists = `-- name: SelectTimeExists :one
select exists(
  select 1 from time
  where leaderboard_id = ?
  and player_id = ?
  and duration = ?
)
`

type SelectTimeExistsParams struct {
	LeaderboardID int64
	PlayerID      string
	Duration      float64
}

func (q *Queries) SelectTimeExists(ctx context.Context, arg SelectTimeExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectTimeExists, arg.LeaderboardID, arg.PlayerID, arg.Duration)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const selectTimesFromLeaderboard = `-- name: SelectTimesFromLeaderboard :many
select time.id, time.leaderboard_id, time.player_id, time.tempus_time_id, time.duration, time.verified, time.created_at, player.id, player.role, player.alias, player.soldier_div, player.demo_div, player.avatar_url, player.trade_token, player.tempus_id, player.country, player.country_code, player.class_pref, player.map_pref, player.launcher_pref, player.created_at from time
  join player on time.player_id = player.id
  where time.leaderboard_id = ?
  order by time.duration asc
`

type SelectTimesFromLeaderboardRow struct {
	Time   Time
	Player Player
}

func (q *Queries) SelectTimesFromLeaderboard(ctx context.Context, leaderboardID int64) ([]SelectTimesFromLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, selectTimesFromLeaderboard, leaderboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectTimesFromLeaderboardRow
	for rows.Next() {
		var i SelectTimesFromLeaderboardRow
		if err := rows.Scan(
			&i.Time.ID,
			&i.Time.LeaderboardID,
			&i.Time.PlayerID,
			&i.Time.TempusTimeID,
			&i.Time.Duration,
			&i.Time.Verified,
			&i.Time.CreatedAt,
			&i.Player.ID,
			&i.Player.Role,
			&i.Player.Alias,
			&i.Player.SoldierDiv,
			&i.Player.DemoDiv,
			&i.Player.AvatarUrl,
			&i.Player.TradeToken,
			&i.Player.TempusID,
			&i.Player.Country,
			&i.Player.CountryCode,
			&i.Player.ClassPref,
			&i.Player.MapPref,
			&i.Player.LauncherPref,
			&i.Player.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeFromTempus = `-- name: UpdateTimeFromTempus :exec
update time
  set duration = ?,
  tempus_time_id = ?,
  created_at = ?
  where id = ?
`

type UpdateTimeFromTempusParams struct {
	Duration     float64
	TempusTimeID sql.NullInt64
	CreatedAt    time.Time
	ID           int64
}

func (q *Queries) UpdateTimeFromTempus(ctx context.Context, arg UpdateTimeFromTempusParams) error {
	_, err := q.db.ExecContext(ctx, updateTimeFromTempus,
		arg.Duration,
		arg.TempusTimeID,
		arg.CreatedAt,
		arg.ID,
	)
	return err
}

const verifyTime = `-- name: VerifyTime :exec
update time
  set verified = true
  where id = ?
`

func (q *Queries) VerifyTime(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, verifyTime, id)
	return err
}
